### ISSUE TITLE
Feature request: Supporting unix socket files

### ISSUE THREAD

**Issue by Alessar** [borisermakof/serilog-sinks-fluentd#6]
Plugin works. It is good. But looks like it uses tcp socket for transfer data into `fluentd`.
It will be good, if it can additionally support sending data via unix socket files.
Format of sending logs it is the same (Fluentd plugins `in_forward` and `in_unix` have the same transport protocol for input records).

**Comment by igprya** [comment]
Hey! 🙂 
I'm almost done implementing UDS support, should be ready in a few days.

**Comment by borisermakof** [comment]
@igprya Good news!) we are waiting

**Comment by igprya** [comment]
Just submitted the PR #7, come take a look! 🙂

**Comment by borisermakof** [comment]
Merged. Thanks @igprya
